# Generated by Django 3.2 on 2022-08-31 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('studentId', models.CharField(max_length=11)),
                ('userId', models.BigIntegerField()),
                ('firstname', models.CharField(blank=True, max_length=50)),
                ('middlename', models.CharField(blank=True, max_length=50)),
                ('lastname', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
