# Generated by Django 3.2.5 on 2024-12-11 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import event.models
import private_storage.fields
import private_storage.storage.files


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignSkillToSkillgroup',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('goal_point', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('start_datetime', models.DateTimeField(null=True)),
                ('end_datetime', models.DateTimeField(null=True)),
                ('info', models.CharField(blank=True, default='', max_length=200)),
                ('approved', models.BooleanField(default=False)),
                ('used_for_calculation', models.BooleanField(default=False)),
                ('arranged_inside', models.BooleanField(default=False)),
                ('attachment_link', models.URLField(blank=True, default='')),
                ('attachment_file', private_storage.fields.PrivateFileField(blank=True, max_length=500, null=True, storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to=event.models.event_attachment_file_directory_path)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_approved_by_set', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_created_by_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('info', models.CharField(blank=True, default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Skillgroup',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('info', models.CharField(default='', max_length=200)),
                ('skills', models.ManyToManyField(null=True, related_name='skillgroup_skill_set', through='event.AssignSkillToSkillgroup', to='event.Skill')),
            ],
        ),
        migrations.CreateModel(
            name='EventAttendance',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('university_id', models.CharField(max_length=11)),
                ('firstname', models.CharField(blank=True, default='', max_length=50)),
                ('middlename', models.CharField(blank=True, default='', max_length=50)),
                ('lastname', models.CharField(blank=True, default='', max_length=50)),
                ('synced', models.BooleanField(default=False)),
                ('used_for_calculation', models.BooleanField(default=False)),
                ('event_id_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
                ('user_id_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='skills',
            field=models.ManyToManyField(null=True, related_name='event_skill_set', to='event.Skill'),
        ),
        migrations.AddField(
            model_name='event',
            name='staffs',
            field=models.ManyToManyField(null=True, related_name='event_staff_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('th_name', models.CharField(blank=True, default='', max_length=50)),
                ('en_name', models.CharField(blank=True, default='', max_length=50)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('info', models.CharField(default='', max_length=200)),
                ('attachment_file', private_storage.fields.PrivateFileField(blank=True, max_length=500, null=True, storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to=event.models.curriculum_attachment_file_directory_path)),
                ('skillgroups', models.ManyToManyField(null=True, related_name='curriculum_skillgroup_set', to='event.Skillgroup')),
            ],
        ),
        migrations.AddField(
            model_name='assignskilltoskillgroup',
            name='skill_id_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignskilltoskillgroup_skill_set', to='event.skill'),
        ),
        migrations.AddField(
            model_name='assignskilltoskillgroup',
            name='skillgroup_id_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignskilltoskillgroup_skillgroup_set', to='event.skillgroup'),
        ),
    ]
