# Generated by Django 3.2.5 on 2022-12-21 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curriculumskillgroup',
            name='curriculum_id_fk',
        ),
        migrations.RemoveField(
            model_name='curriculumskillgroup',
            name='skill_group_id_fk',
        ),
        migrations.AddField(
            model_name='curriculum',
            name='skillgroups',
            field=models.ManyToManyField(null=True, related_name='curriculum_skillgroup_set', to='event.SkillGroup'),
        ),
        migrations.AddField(
            model_name='skillgroup',
            name='skills',
            field=models.ManyToManyField(null=True, related_name='skillgroup_skill_set', to='event.Skill'),
        ),
        migrations.DeleteModel(
            name='AssignSkillToSkillGroup',
        ),
        migrations.DeleteModel(
            name='CurriculumSKillGroup',
        ),
    ]
