# Generated by Django 3.2.5 on 2022-12-17 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='skills',
            field=models.ManyToManyField(related_name='event_skill_set', to='event.Skill'),
        ),
        migrations.DeleteModel(
            name='EventSkill',
        ),
    ]
