# Generated by Django 3.2.5 on 2022-12-17 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20221217_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='skills',
            field=models.ManyToManyField(null=True, related_name='event_skill_set', to='event.Skill'),
        ),
    ]
