# Generated by Django 3.2 on 2022-09-08 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20220908_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='created_by',
            field=models.BigIntegerField(default=0),
        ),
    ]
