# Generated by Django 3.2.5 on 2022-12-18 03:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0003_alter_event_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='staffs',
            field=models.ManyToManyField(null=True, related_name='event_staff_set', to='staff.Staff'),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_created_by_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
