# Generated by Django 3.2 on 2022-09-08 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_event_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='created_by',
            field=models.BigIntegerField(),
        ),
    ]
