# Generated by Django 3.2.5 on 2022-12-18 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
        ('event', '0004_auto_20221218_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentattendevent',
            name='user_id_fk',
        ),
        migrations.AddField(
            model_name='studentattendevent',
            name='student_id_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.student'),
        ),
    ]
