# Generated by Django 3.2 on 2022-09-12 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_alter_event_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='created_by',
            field=models.BigIntegerField(editable=False),
        ),
    ]
