# Generated by Django 3.2 on 2022-09-12 15:08

from django.db import migrations, models
import djongo.storage


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_alter_event_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attachment_file',
            field=models.FileField(blank=True, null=True, storage=djongo.storage.GridFSStorage(base_url='student_portfolio.urlsfiles/', collection='files'), upload_to='events'),
        ),
        migrations.AddField(
            model_name='event',
            name='attachment_link',
            field=models.URLField(blank=True, default=''),
        ),
    ]
