# Generated by Django 3.2 on 2022-09-29 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_alter_event_attachment_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skillId', models.BigIntegerField()),
                ('point', models.BigIntegerField(default=0)),
            ],
        ),
    ]
