# Generated by Django 3.2 on 2022-09-29 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_alter_skillgoal_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SkillGoal',
        ),
        migrations.AddField(
            model_name='skill',
            name='goal_point',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='skill',
            name='type',
            field=models.IntegerField(default=0),
        ),
    ]
