# Generated by Django 3.2.5 on 2023-01-17 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_alter_curriculum_skillgroups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='goal_point',
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='skillgroups',
            field=models.ManyToManyField(null=True, related_name='curriculum_skillgroup_set', to='event.Skillgroup'),
        ),
    ]
