# Generated by Django 3.2.5 on 2023-01-17 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0014_alter_curriculum_skillgroups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillgroup',
            name='skills',
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='skillgroups',
            field=models.ManyToManyField(null=True, related_name='curriculum_skillgroup_set', to='event.Skillgroup'),
        ),
        migrations.CreateModel(
            name='AssignSkillToSkillgroup',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('goal_point', models.BigIntegerField(default=0)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.skill')),
                ('skillgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.skillgroup')),
            ],
        ),
    ]
