# Generated by Django 3.2.5 on 2023-01-17 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0015_auto_20230117_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillgroup',
            name='skills',
            field=models.ManyToManyField(null=True, related_name='skillgroup_skill_set', through='event.AssignSkillToSkillgroup', to='event.Skill'),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='skillgroups',
            field=models.ManyToManyField(null=True, related_name='curriculum_skillgroup_set', to='event.Skillgroup'),
        ),
    ]
