# Generated by Django 3.2.5 on 2023-01-17 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0016_auto_20230117_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignskilltoskillgroup',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignskilltoskillgroup_skill_set', to='event.skill'),
        ),
        migrations.AlterField(
            model_name='assignskilltoskillgroup',
            name='skillgroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignskilltoskillgroup_skillgroup_set', to='event.skillgroup'),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='skillgroups',
            field=models.ManyToManyField(null=True, related_name='curriculum_skillgroup_set', to='event.Skillgroup'),
        ),
    ]
