# Generated by Django 3.2.5 on 2023-01-17 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0018_auto_20230117_1428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignskilltoskillgroup',
            old_name='skillgroup_id',
            new_name='skillgroup_id_fk',
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='skillgroups',
            field=models.ManyToManyField(null=True, related_name='curriculum_skillgroup_set', to='event.Skillgroup'),
        ),
    ]
