# Generated by Django 3.2.5 on 2023-03-22 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0033_auto_20230321_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='info',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='skillgroups',
            field=models.ManyToManyField(null=True, related_name='curriculum_skillgroup_set', to='event.Skillgroup'),
        ),
    ]
