# Generated by Django 3.2 on 2022-10-06 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='projectId',
            new_name='id',
        ),
    ]
