# Generated by Django 3.2.5 on 2023-01-05 06:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20230105_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2023, 1, 5, 6, 52, 8, 266458, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2023, 1, 5, 6, 52, 8, 266458, tzinfo=utc)),
        ),
    ]
