# Generated by Django 3.2 on 2022-10-06 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_rename_projectid_project_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='id',
            new_name='projectId',
        ),
    ]
