# Generated by Django 3.2.5 on 2023-01-05 13:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20230105_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2023, 1, 5, 13, 34, 33, 69322, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2023, 1, 5, 13, 34, 33, 69322, tzinfo=utc)),
        ),
    ]
