# Generated by Django 3.2.5 on 2023-01-05 13:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20230105_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2023, 1, 5, 13, 35, 46, 101934, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2023, 1, 5, 13, 35, 46, 101934, tzinfo=utc)),
        ),
    ]
