# Generated by Django 3.2.5 on 2023-02-23 07:39

from django.db import migrations
import private_storage.fields
import private_storage.storage.files
import project.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20230105_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='attachment_file',
            field=private_storage.fields.PrivateFileField(blank=True, max_length=500, null=True, storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to=project.models.project_attachment_file_directory_path),
        ),
    ]
