# Generated by Django 5.1.4 on 2024-12-10 04:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyRole',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('university_id', models.CharField(blank=True, default='', max_length=11, unique=True)),
                ('firstname', models.CharField(blank=True, default='', max_length=50)),
                ('middlename', models.CharField(blank=True, default='', max_length=50)),
                ('lastname', models.CharField(blank=True, default='', max_length=50)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('enroll', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userprofile_enroll_set', to='event.curriculum')),
                ('faculty_role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_profile.facultyrole')),
                ('user_id_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
