# Generated by Django 3.2.5 on 2022-12-21 04:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyRole',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('university_id', models.CharField(blank=True, default='', max_length=11)),
                ('firstname', models.CharField(blank=True, default='', max_length=50)),
                ('middlename', models.CharField(blank=True, default='', max_length=50)),
                ('lastname', models.CharField(blank=True, default='', max_length=50)),
                ('faculty_role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_profile.facultyrole')),
                ('user_id_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
