# Generated by Django 3.2.5 on 2022-12-21 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20221221_1423'),
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='enroll',
            field=models.ManyToManyField(null=True, related_name='userprofile_enroll_set', to='event.Curriculum'),
        ),
    ]
