# Generated by Django 3.2.5 on 2022-12-21 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20221221_1423'),
        ('user_profile', '0002_userprofile_enroll'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='enroll',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='enroll',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userprofile_enroll_set', to='event.curriculum'),
        ),
    ]
