# Generated by Django 3.2.5 on 2023-01-27 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0023_alter_curriculum_skillgroups'),
        ('user_profile', '0003_auto_20221221_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='enroll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userprofile_enroll_set', to='event.curriculum'),
        ),
    ]
