# Generated by Django 3.2.5 on 2023-04-04 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_userprofile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='university_id',
            field=models.CharField(blank=True, default='', max_length=11, unique=True),
        ),
    ]
