# Generated by Django 3.2.5 on 2023-01-05 13:35

import award.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0008_alter_curriculum_skillgroups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('rank', models.IntegerField(null=True)),
                ('received_date', models.DateField(default=datetime.datetime(2023, 1, 5, 13, 35, 46, 105934, tzinfo=utc))),
                ('info', models.CharField(blank=True, default='', max_length=200)),
                ('approved', models.BooleanField(default=False)),
                ('used_for_calculation', models.BooleanField(default=False)),
                ('attachment_link', models.URLField(blank=True, default='')),
                ('attachment_file', models.FileField(blank=True, null=True, upload_to=award.models.award_attachment_file_directory_path)),
                ('approved_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='award_approved_by_set', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='award_created_by_set', to=settings.AUTH_USER_MODEL)),
                ('receivers', models.ManyToManyField(null=True, related_name='award_receiver_set', to=settings.AUTH_USER_MODEL)),
                ('skills', models.ManyToManyField(null=True, related_name='award_skill_set', to='event.Skill')),
                ('supervisors', models.ManyToManyField(null=True, related_name='award_supervisor_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
