# Generated by Django 5.1.4 on 2024-12-10 04:52

import award.models
import datetime
import django.db.models.deletion
import private_storage.fields
import private_storage.storage.files
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('rank', models.IntegerField(default=0)),
                ('received_date', models.DateField(default=datetime.date.today)),
                ('info', models.CharField(blank=True, default='', max_length=200)),
                ('approved', models.BooleanField(default=False)),
                ('used_for_calculation', models.BooleanField(default=False)),
                ('attachment_link', models.URLField(blank=True, default='')),
                ('attachment_file', private_storage.fields.PrivateFileField(blank=True, max_length=500, null=True, storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to=award.models.award_attachment_file_directory_path)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='award_approved_by_set', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='award_created_by_set', to=settings.AUTH_USER_MODEL)),
                ('receivers', models.ManyToManyField(null=True, related_name='award_receiver_set', to=settings.AUTH_USER_MODEL)),
                ('skills', models.ManyToManyField(null=True, related_name='award_skill_set', to='event.skill')),
                ('supervisors', models.ManyToManyField(null=True, related_name='award_supervisor_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
