# Generated by Django 3.2.5 on 2023-01-05 13:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='received_date',
            field=models.DateField(default=datetime.datetime(2023, 1, 5, 13, 36, 19, 976199, tzinfo=utc)),
        ),
    ]
