# Generated by Django 3.2.5 on 2023-01-05 13:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0002_alter_award_received_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='received_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
