# Generated by Django 3.2.5 on 2023-01-05 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0003_alter_award_received_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
