# Generated by Django 3.2.5 on 2023-01-26 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('award', '0005_alter_award_approved_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='award_approved_by_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
