# Generated by Django 3.2.5 on 2023-02-23 07:47

import award.models
from django.db import migrations
import private_storage.fields
import private_storage.storage.files


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0006_alter_award_approved_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='attachment_file',
            field=private_storage.fields.PrivateFileField(blank=True, max_length=500, null=True, storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to=award.models.award_attachment_file_directory_path),
        ),
    ]
