# Generated by Django 3.2.5 on 2023-03-21 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('award', '0007_alter_award_attachment_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='award_created_by_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
