# Generated by Django 3.2.5 on 2023-03-28 13:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0008_alter_award_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='received_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
